name: Automated Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install lua
        uses: leafo/gh-actions-lua@v6
        with:
          luaVersion: 5.3

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v2

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Lint sources
        run: |
          luacheck core plugins tests/test_*.lua
          python tests/test_locales.py

      # TODO: write script to iterate and run multiple test files
      - name: Run tests
        run: lua test_class.lua
        working-directory: tests
