name: Automated Release

on:
  push:
    tags:
      - "[0-9][0-9]_[a-zA-Z]+-v[0-9]+"
      - "[0-9][0-9]_[a-zA-Z]+-v[0-9]+.alpha[0-9]+"
      - "[0-9][0-9]_[a-zA-Z]+-v[0-9]+.beta[0-9]+"

jobs:
  build:
    name: Release Addon
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Populate variables based on $GITHUB_REF
      - name: Parse $GITHUB_REF
        id: pref
        run: |
          export NAME_VER=${GITHUB_REF#*_}
          echo "::set-output name=name::${NAME_VER%-*}"
          echo "::set-output name=version::${NAME_VER#*-v}"
          echo "::set-output name=zip::HandyNotes_${NAME_VER}.zip"
          if [[ $GITHUB_REF =~ .*(alpha|beta).* ]]; then
              echo "::set-output name=prerelease::true"
          else
              echo "::set-output name=prerelease::false"
          fi

      # Build release artifacts
      - name: Build release
        run: python release.py ${GITHUB_REF:10}

      # Create GitHub release and upload the .zip file
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.pref.outputs.name }} v${{ steps.pref.outputs.version }}
          body_path: release/CHANGELOG.partial.md
          files: release/${{ steps.pref.outputs.zip }}
          prerelease: ${{ steps.pref.outputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
